/*
Reward Cloud

It is an API for Reward Cloud project in ITG Commerce

API version: v0.7.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rewardcloud

import (
	"encoding/json"
	"fmt"
)

// ServiceAccountProjectOutputServiceAccountRegistry struct for ServiceAccountProjectOutputServiceAccountRegistry
type ServiceAccountProjectOutputServiceAccountRegistry struct {
	ServiceAccountRegistryProjectOutput *ServiceAccountRegistryProjectOutput
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ServiceAccountProjectOutputServiceAccountRegistry) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into ServiceAccountRegistryProjectOutput
	err = json.Unmarshal(data, &dst.ServiceAccountRegistryProjectOutput)
	if err == nil {
		jsonServiceAccountRegistryProjectOutput, _ := json.Marshal(dst.ServiceAccountRegistryProjectOutput)
		if string(jsonServiceAccountRegistryProjectOutput) == "{}" { // empty struct
			dst.ServiceAccountRegistryProjectOutput = nil
		} else {
			return nil // data stored in dst.ServiceAccountRegistryProjectOutput, return on the first match
		}
	} else {
		dst.ServiceAccountRegistryProjectOutput = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ServiceAccountProjectOutputServiceAccountRegistry)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ServiceAccountProjectOutputServiceAccountRegistry) MarshalJSON() ([]byte, error) {
	if src.ServiceAccountRegistryProjectOutput != nil {
		return json.Marshal(&src.ServiceAccountRegistryProjectOutput)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableServiceAccountProjectOutputServiceAccountRegistry struct {
	value *ServiceAccountProjectOutputServiceAccountRegistry
	isSet bool
}

func (v NullableServiceAccountProjectOutputServiceAccountRegistry) Get() *ServiceAccountProjectOutputServiceAccountRegistry {
	return v.value
}

func (v *NullableServiceAccountProjectOutputServiceAccountRegistry) Set(val *ServiceAccountProjectOutputServiceAccountRegistry) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountProjectOutputServiceAccountRegistry) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountProjectOutputServiceAccountRegistry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountProjectOutputServiceAccountRegistry(val *ServiceAccountProjectOutputServiceAccountRegistry) *NullableServiceAccountProjectOutputServiceAccountRegistry {
	return &NullableServiceAccountProjectOutputServiceAccountRegistry{value: val, isSet: true}
}

func (v NullableServiceAccountProjectOutputServiceAccountRegistry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountProjectOutputServiceAccountRegistry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
