/*
Reward Cloud

It is an API for Reward Cloud project in ITG Commerce

API version: v0.7.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rewardcloud

import (
	"encoding/json"
	"fmt"
)

// ProductProductInputDefaultPrice struct for ProductProductInputDefaultPrice
type ProductProductInputDefaultPrice struct {
	PriceProductInput *PriceProductInput
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ProductProductInputDefaultPrice) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into PriceProductInput
	err = json.Unmarshal(data, &dst.PriceProductInput)
	if err == nil {
		jsonPriceProductInput, _ := json.Marshal(dst.PriceProductInput)
		if string(jsonPriceProductInput) == "{}" { // empty struct
			dst.PriceProductInput = nil
		} else {
			return nil // data stored in dst.PriceProductInput, return on the first match
		}
	} else {
		dst.PriceProductInput = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ProductProductInputDefaultPrice)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ProductProductInputDefaultPrice) MarshalJSON() ([]byte, error) {
	if src.PriceProductInput != nil {
		return json.Marshal(&src.PriceProductInput)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableProductProductInputDefaultPrice struct {
	value *ProductProductInputDefaultPrice
	isSet bool
}

func (v NullableProductProductInputDefaultPrice) Get() *ProductProductInputDefaultPrice {
	return v.value
}

func (v *NullableProductProductInputDefaultPrice) Set(val *ProductProductInputDefaultPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableProductProductInputDefaultPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableProductProductInputDefaultPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductProductInputDefaultPrice(val *ProductProductInputDefaultPrice) *NullableProductProductInputDefaultPrice {
	return &NullableProductProductInputDefaultPrice{value: val, isSet: true}
}

func (v NullableProductProductInputDefaultPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductProductInputDefaultPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
