/*
Reward Cloud

It is an API for Reward Cloud project in ITG Commerce

API version: v0.6.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rewardcloud

import (
	"encoding/json"
	"time"
)

// Region Class Region
type Region struct {
	Id                 *int32         `json:"id,omitempty"`
	Uuid               NullableString `json:"uuid,omitempty"`
	Name               NullableString `json:"name,omitempty"`
	KubecostUrl        NullableString `json:"kubecostUrl,omitempty"`
	KubecostUser       NullableString `json:"kubecostUser,omitempty"`
	KubecostPass       NullableString `json:"kubecostPass,omitempty"`
	ChangeKubecostPass NullableString `json:"changeKubecostPass,omitempty"`
	IsDefault          NullableBool   `json:"isDefault,omitempty"`
	Environment        []string       `json:"environment,omitempty"`
	Provider           NullableString `json:"provider,omitempty"`
	Products           []string       `json:"products,omitempty"`
	CreatedBy          NullableString `json:"createdBy,omitempty"`
	UpdatedBy          NullableString `json:"updatedBy,omitempty"`
	CreatedAt          *time.Time     `json:"createdAt,omitempty"`
	UpdatedAt          *time.Time     `json:"updatedAt,omitempty"`
}

// NewRegion instantiates a new Region object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegion() *Region {
	this := Region{}
	return &this
}

// NewRegionWithDefaults instantiates a new Region object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionWithDefaults() *Region {
	this := Region{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Region) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Region) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Region) SetId(v int32) {
	o.Id = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetUuid() string {
	if o == nil || isNil(o.Uuid.Get()) {
		var ret string
		return ret
	}
	return *o.Uuid.Get()
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Uuid.Get(), o.Uuid.IsSet()
}

// HasUuid returns a boolean if a field has been set.
func (o *Region) HasUuid() bool {
	if o != nil && o.Uuid.IsSet() {
		return true
	}

	return false
}

// SetUuid gets a reference to the given NullableString and assigns it to the Uuid field.
func (o *Region) SetUuid(v string) {
	o.Uuid.Set(&v)
}

// SetUuidNil sets the value for Uuid to be an explicit nil
func (o *Region) SetUuidNil() {
	o.Uuid.Set(nil)
}

// UnsetUuid ensures that no value is present for Uuid, not even an explicit nil
func (o *Region) UnsetUuid() {
	o.Uuid.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetName() string {
	if o == nil || isNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *Region) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *Region) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *Region) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *Region) UnsetName() {
	o.Name.Unset()
}

// GetKubecostUrl returns the KubecostUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetKubecostUrl() string {
	if o == nil || isNil(o.KubecostUrl.Get()) {
		var ret string
		return ret
	}
	return *o.KubecostUrl.Get()
}

// GetKubecostUrlOk returns a tuple with the KubecostUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetKubecostUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KubecostUrl.Get(), o.KubecostUrl.IsSet()
}

// HasKubecostUrl returns a boolean if a field has been set.
func (o *Region) HasKubecostUrl() bool {
	if o != nil && o.KubecostUrl.IsSet() {
		return true
	}

	return false
}

// SetKubecostUrl gets a reference to the given NullableString and assigns it to the KubecostUrl field.
func (o *Region) SetKubecostUrl(v string) {
	o.KubecostUrl.Set(&v)
}

// SetKubecostUrlNil sets the value for KubecostUrl to be an explicit nil
func (o *Region) SetKubecostUrlNil() {
	o.KubecostUrl.Set(nil)
}

// UnsetKubecostUrl ensures that no value is present for KubecostUrl, not even an explicit nil
func (o *Region) UnsetKubecostUrl() {
	o.KubecostUrl.Unset()
}

// GetKubecostUser returns the KubecostUser field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetKubecostUser() string {
	if o == nil || isNil(o.KubecostUser.Get()) {
		var ret string
		return ret
	}
	return *o.KubecostUser.Get()
}

// GetKubecostUserOk returns a tuple with the KubecostUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetKubecostUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KubecostUser.Get(), o.KubecostUser.IsSet()
}

// HasKubecostUser returns a boolean if a field has been set.
func (o *Region) HasKubecostUser() bool {
	if o != nil && o.KubecostUser.IsSet() {
		return true
	}

	return false
}

// SetKubecostUser gets a reference to the given NullableString and assigns it to the KubecostUser field.
func (o *Region) SetKubecostUser(v string) {
	o.KubecostUser.Set(&v)
}

// SetKubecostUserNil sets the value for KubecostUser to be an explicit nil
func (o *Region) SetKubecostUserNil() {
	o.KubecostUser.Set(nil)
}

// UnsetKubecostUser ensures that no value is present for KubecostUser, not even an explicit nil
func (o *Region) UnsetKubecostUser() {
	o.KubecostUser.Unset()
}

// GetKubecostPass returns the KubecostPass field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetKubecostPass() string {
	if o == nil || isNil(o.KubecostPass.Get()) {
		var ret string
		return ret
	}
	return *o.KubecostPass.Get()
}

// GetKubecostPassOk returns a tuple with the KubecostPass field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetKubecostPassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KubecostPass.Get(), o.KubecostPass.IsSet()
}

// HasKubecostPass returns a boolean if a field has been set.
func (o *Region) HasKubecostPass() bool {
	if o != nil && o.KubecostPass.IsSet() {
		return true
	}

	return false
}

// SetKubecostPass gets a reference to the given NullableString and assigns it to the KubecostPass field.
func (o *Region) SetKubecostPass(v string) {
	o.KubecostPass.Set(&v)
}

// SetKubecostPassNil sets the value for KubecostPass to be an explicit nil
func (o *Region) SetKubecostPassNil() {
	o.KubecostPass.Set(nil)
}

// UnsetKubecostPass ensures that no value is present for KubecostPass, not even an explicit nil
func (o *Region) UnsetKubecostPass() {
	o.KubecostPass.Unset()
}

// GetChangeKubecostPass returns the ChangeKubecostPass field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetChangeKubecostPass() string {
	if o == nil || isNil(o.ChangeKubecostPass.Get()) {
		var ret string
		return ret
	}
	return *o.ChangeKubecostPass.Get()
}

// GetChangeKubecostPassOk returns a tuple with the ChangeKubecostPass field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetChangeKubecostPassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangeKubecostPass.Get(), o.ChangeKubecostPass.IsSet()
}

// HasChangeKubecostPass returns a boolean if a field has been set.
func (o *Region) HasChangeKubecostPass() bool {
	if o != nil && o.ChangeKubecostPass.IsSet() {
		return true
	}

	return false
}

// SetChangeKubecostPass gets a reference to the given NullableString and assigns it to the ChangeKubecostPass field.
func (o *Region) SetChangeKubecostPass(v string) {
	o.ChangeKubecostPass.Set(&v)
}

// SetChangeKubecostPassNil sets the value for ChangeKubecostPass to be an explicit nil
func (o *Region) SetChangeKubecostPassNil() {
	o.ChangeKubecostPass.Set(nil)
}

// UnsetChangeKubecostPass ensures that no value is present for ChangeKubecostPass, not even an explicit nil
func (o *Region) UnsetChangeKubecostPass() {
	o.ChangeKubecostPass.Unset()
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetIsDefault() bool {
	if o == nil || isNil(o.IsDefault.Get()) {
		var ret bool
		return ret
	}
	return *o.IsDefault.Get()
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetIsDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsDefault.Get(), o.IsDefault.IsSet()
}

// HasIsDefault returns a boolean if a field has been set.
func (o *Region) HasIsDefault() bool {
	if o != nil && o.IsDefault.IsSet() {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given NullableBool and assigns it to the IsDefault field.
func (o *Region) SetIsDefault(v bool) {
	o.IsDefault.Set(&v)
}

// SetIsDefaultNil sets the value for IsDefault to be an explicit nil
func (o *Region) SetIsDefaultNil() {
	o.IsDefault.Set(nil)
}

// UnsetIsDefault ensures that no value is present for IsDefault, not even an explicit nil
func (o *Region) UnsetIsDefault() {
	o.IsDefault.Unset()
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *Region) GetEnvironment() []string {
	if o == nil || isNil(o.Environment) {
		var ret []string
		return ret
	}
	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetEnvironmentOk() ([]string, bool) {
	if o == nil || isNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *Region) HasEnvironment() bool {
	if o != nil && !isNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given []string and assigns it to the Environment field.
func (o *Region) SetEnvironment(v []string) {
	o.Environment = v
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetProvider() string {
	if o == nil || isNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *Region) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *Region) SetProvider(v string) {
	o.Provider.Set(&v)
}

// SetProviderNil sets the value for Provider to be an explicit nil
func (o *Region) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *Region) UnsetProvider() {
	o.Provider.Unset()
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *Region) GetProducts() []string {
	if o == nil || isNil(o.Products) {
		var ret []string
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetProductsOk() ([]string, bool) {
	if o == nil || isNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *Region) HasProducts() bool {
	if o != nil && !isNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []string and assigns it to the Products field.
func (o *Region) SetProducts(v []string) {
	o.Products = v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetCreatedBy() string {
	if o == nil || isNil(o.CreatedBy.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedBy.Get()
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBy.Get(), o.CreatedBy.IsSet()
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *Region) HasCreatedBy() bool {
	if o != nil && o.CreatedBy.IsSet() {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given NullableString and assigns it to the CreatedBy field.
func (o *Region) SetCreatedBy(v string) {
	o.CreatedBy.Set(&v)
}

// SetCreatedByNil sets the value for CreatedBy to be an explicit nil
func (o *Region) SetCreatedByNil() {
	o.CreatedBy.Set(nil)
}

// UnsetCreatedBy ensures that no value is present for CreatedBy, not even an explicit nil
func (o *Region) UnsetCreatedBy() {
	o.CreatedBy.Unset()
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Region) GetUpdatedBy() string {
	if o == nil || isNil(o.UpdatedBy.Get()) {
		var ret string
		return ret
	}
	return *o.UpdatedBy.Get()
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Region) GetUpdatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedBy.Get(), o.UpdatedBy.IsSet()
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *Region) HasUpdatedBy() bool {
	if o != nil && o.UpdatedBy.IsSet() {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given NullableString and assigns it to the UpdatedBy field.
func (o *Region) SetUpdatedBy(v string) {
	o.UpdatedBy.Set(&v)
}

// SetUpdatedByNil sets the value for UpdatedBy to be an explicit nil
func (o *Region) SetUpdatedByNil() {
	o.UpdatedBy.Set(nil)
}

// UnsetUpdatedBy ensures that no value is present for UpdatedBy, not even an explicit nil
func (o *Region) UnsetUpdatedBy() {
	o.UpdatedBy.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Region) GetCreatedAt() time.Time {
	if o == nil || isNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Region) HasCreatedAt() bool {
	if o != nil && !isNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Region) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Region) GetUpdatedAt() time.Time {
	if o == nil || isNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Region) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Region) HasUpdatedAt() bool {
	if o != nil && !isNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Region) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Region) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Uuid.IsSet() {
		toSerialize["uuid"] = o.Uuid.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.KubecostUrl.IsSet() {
		toSerialize["kubecostUrl"] = o.KubecostUrl.Get()
	}
	if o.KubecostUser.IsSet() {
		toSerialize["kubecostUser"] = o.KubecostUser.Get()
	}
	if o.KubecostPass.IsSet() {
		toSerialize["kubecostPass"] = o.KubecostPass.Get()
	}
	if o.ChangeKubecostPass.IsSet() {
		toSerialize["changeKubecostPass"] = o.ChangeKubecostPass.Get()
	}
	if o.IsDefault.IsSet() {
		toSerialize["isDefault"] = o.IsDefault.Get()
	}
	if !isNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if !isNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	if o.CreatedBy.IsSet() {
		toSerialize["createdBy"] = o.CreatedBy.Get()
	}
	if o.UpdatedBy.IsSet() {
		toSerialize["updatedBy"] = o.UpdatedBy.Get()
	}
	if !isNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !isNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableRegion struct {
	value *Region
	isSet bool
}

func (v NullableRegion) Get() *Region {
	return v.value
}

func (v *NullableRegion) Set(val *Region) {
	v.value = val
	v.isSet = true
}

func (v NullableRegion) IsSet() bool {
	return v.isSet
}

func (v *NullableRegion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegion(val *Region) *NullableRegion {
	return &NullableRegion{value: val, isSet: true}
}

func (v NullableRegion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
