disallowAdditionalPropertiesIfNotPresent: true
packageName: rewardcloud
useOneOfDiscriminatorLookup: true
isGoSubmodule: false
enumClassPrefix: false
structPrefix: true
validateSpec: false
generateInterfaces: false
prependFormOrBodyParameters: true